"""
Data load script for dim_customer.
Generated by SAS-to-Snowflake Migration Toolkit.
"""
from snowflake.snowpark import Session


def load_dim_customer(session: Session, stage_name: str = "@sas_migration_stage"):
    """Load dim_customer from staged CSV files."""

    # COPY INTO from staged files
    session.sql(f"""
        COPY INTO SAS_MIGRATION.RAW.DIM_CUSTOMER
        FROM {stage_name}/customers_raw.csv
        FILE_FORMAT = (
            TYPE = 'CSV'
            FIELD_OPTIONALLY_ENCLOSED_BY = '"'
            SKIP_HEADER = 1
            NULL_IF = ('', 'NULL', '.')
        )
        ON_ERROR = 'CONTINUE'
    """).collect()

    # Validate row count
    result = session.sql("SELECT COUNT(*) AS cnt FROM SAS_MIGRATION.RAW.DIM_CUSTOMER").collect()
    print(f"Loaded {result[0]['CNT']} rows into DIM_CUSTOMER")


if __name__ == "__main__":
    connection_params = {
        "account": "<account>",
        "user": "<user>",
        "password": "<password>",
        "warehouse": "MIGRATION_WH",
        "database": "SAS_MIGRATION",
        "schema": "RAW",
    }
    session = Session.builder.configs(connection_params).create()
    load_dim_customer(session)
    session.close()
